myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('chatbot_response/', views.chatbot_response, name='chatbot_response'),
    path('about', views.about, name='about'),
    path('register', views.register, name='register'),
    # Email verifiction url's
    path('email-verification/<str:uidb64>/<str:token>/', views.email_verification, name='email-verification'),
    path('email-verification-sent', views.email_verification_sent, name='email-verification-sent'),
    path('email-verification-success', views.email_verification_success, name='email-verification-success'),
    path('email-verification-failed', views.email_verification_failed, name='email-verification-failed'),
    # Login & logout url's
    path('my-login', views.my_login, name='my-login'),
    path('user-logout', views.user_logout, name='user-logout'),
    # Account management
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile-management', views.profile_management, name='profile-management'),
    path('delete-account', views.delete_account, name='delete-account'),
    # Password management urls/views
    path('reset_password', auth_views.PasswordResetView.as_view(template_name="account/password/password-reset.html"), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name="account/password/password-reset-sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password/password-reset-form.html"), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name="account/password/password-reset-complete.html"), name='password_reset_complete'),

    path('contact', views.contact, name='contact'),
    path('search', views.search, name='search'),

    # CRUD Section
    # path('destination/<int:destination_id>/', views.destination_detail, name='destination_detail'),
    path('destination/<int:destination_id>/', views.destination_detail, name='destination_detail'),
    path('create', views.create_destination, name='create_destination'),
    path('destination/update/<int:id>/', views.update_destination, name='update_destination'),
    path('destination/delete/<int:id>/', views.delete_destination, name='delete_destination'),
    # User review
    path('destination/<int:destination_id>/add_review/', views.add_review, name='add_review'),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Destination(models.Model):
    WISATA_REGLIGI = 'WR'
    TAMAN_WISATA = 'TW'
    WISATA_AIR = 'WA'
    WISATA_KULINER = 'WK'

    CATEGORY_CHOICES = [
        (WISATA_REGLIGI, 'Wisata Religi'),
        (TAMAN_WISATA, 'Taman Wisata'),
        (WISATA_AIR, 'Wisata Air'),
        (WISATA_KULINER, 'Wisata Kuliner'),
    ]

    BUDGET_0_20000 = '0-20000'
    BUDGET_20000_50000 = '20000-50000'
    BUDGET_50000_100000 = '50000-100000'
    BUDGET_100000_200000 = '100000-200000'

    BUDGET_CHOICES = [
        (BUDGET_0_20000, '0-20000'),
        (BUDGET_20000_50000, '20000-50000'),
        (BUDGET_50000_100000, '50000-100000'),
        (BUDGET_100000_200000, '100000-200000'),
    ]

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='destination_pics', null=True, blank=True)
    description = models.TextField()
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES,default=WISATA_REGLIGI,)
    budget = models.CharField(max_length=13, choices=BUDGET_CHOICES,default=BUDGET_0_20000,)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    youtube_url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    review_text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.user.username} on {self.destination.title}'

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    body {
       background-image: url("{% static 'images/SUNYARAGI.jpeg' %}");
       background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-color: rgba(255,255,255,0.6);
        background-blend-mode: lighten;
     }
   </style>
   <div class="body-background my-auto d-flex align-items-center justify-content-center" style="height: 100vh;">
        <div class="container">
            <!--Nature Image & Text-->
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="custom-h1 text-center fw-bold mb-5">About Us</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <h6 class="text-justify mb-5 ">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Montes nascetur ridiculus mus mauris vitae. Faucibus ornare suspendisse sed nisi lacus sed viverra. Quam viverra orci sagittis eu volutpat odio facilisis. Libero volutpat sed cras ornare arcu dui vivamus. Dui id ornare arcu odio ut. Mattis nunc sed blandit libero volutpat sed cras. Mauris vitae ultricies leo integer malesuada nunc. Iaculis nunc sed augue lacus viverra vitae congue eu. Cursus turpis massa tincidunt dui ut ornare. Eget velit aliquet sagittis id consectetur purus ut. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Sed ullamcorper morbi tincidunt ornare massa eget</h6>
                </div>
            </div>
            <!--End Nature Image-->
        </div>
    </div>
    {% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wisata Cirebon</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  <!--<link rel="stylesheet" href="{% static 'css/styles.css' %}">-->
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
  <!-- Leaflet CSS and JS -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
</head>
<body>
<!-- Awal Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" href="{% url 'index' %}">D Dolanan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active nav1 d-flex" aria-current="page" href="{% url 'index' %}">
             <span class="my-auto">Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav2" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav3" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated and user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link nav4" href="{% url 'create_destination' %}">Create</a>
        </li>
        {% endif %}
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link nav4" href="{% url 'register' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav4" href="{% url 'my-login' %}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link nav4" href="{% url 'user-logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav4" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<br />
<div class="container">
  {% block content %}
  {% endblock content %}
</div>

<!-- Kode JavaScript tambahan akan diletakkan di sini -->
{% block extra_js %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<style>
    body {
    background-image: url("{% static 'images/BATU LAWANG.jpg' %}");
    background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-color: rgba(0,0,0,0.6);
        background-blend-mode: darken;
    }

</style>
<div class="container bg-white shadow-md p-5 col-8 mb-3">
    <h1 class="contact-header">Have a question?</h1>
    <h1 class="contact-header">Contact us!</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="message-item" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br />
        <div class="send-button">
            <button type="submit" class="btn btn-dark">Send Message</button>
            <br />
        </div>
    </form>
    <br>
</div>

{% endblock content %}

templates/create_destination.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-2 mb-3">

    {% if user.is_staff or user.is_superuser %}
    <h2>Create New Destination</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Simpan</button>
    </form>
    {% else %}
    <p>Sorry, you do not have access to this page.</p>
    {% endif %}

</div>

{% endblock %}

templates/delete_destination.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container mt-3 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <h2>Delete Destination</h2>
    <p>Are you sure you want to delete "{{ destination.title }}"?</p>
    <form method="POST">
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'destination_detail' destination.id %}" class="btn btn-primary">Cancel</a>
    </form>
    {% endif %}
</div>

{% endblock content %}

templates/destination_detail.html
{% extends 'base.html' %}
{% load static %}
{% load my_filters %}

{% block content %}

<style>
    .input-review {
        width: 100%; /* Menentukan lebar kolom input */
        height: 200px; /* Menentukan tinggi kolom input */
        margin-bottom: 10px; /* Menambahkan jarak antara kolom input dan tombol submit */
    }

    .submit-button {
        background-color: #4CAF50; /* Warna latar belakang tombol submit */
        color: white; /* Warna teks tombol submit */
        padding: 10px 20px; /* Padding di dalam tombol submit */
        border: none; /* Menghapus border pada tombol submit */
        cursor: pointer; /* Mengubah cursor saat di atas tombol submit */
    }

    .submit-button:hover {
        background-color: #45a049; /* Mengubah warna latar belakang tombol submit saat di-hover */
    }
    .fb-share-wrapper {
        display: flex;
        justify-content: center;  /* Center horizontally */
        align-items: center;      /* Center vertically */
      }

      .custom-fb-share-button {
        transform: scale(2);  /* Membuat ukuran tombol */
      }

    </style>

<!-- Messages -->
{% for message in messages %}
    <div class="alert alert-success">{{ message }}</div>
{% endfor %}

<!--Flower Image and Cards-->
<div class="row">
    <div class="col-sm-8">
        <h1 class="mt-3 title-text">{{ destination.title }}</h1>
        <img src="{{ destination.image.url }}" alt="{{ destination.title }}" class="flower-image mt-4">
        <p class="mt-4 description-text">{{ destination.description }}</p>
        <p class="">Category: {{ destination.get_category_display }}</p>
        <p class="">Budget: {{ destination.get_budget_display }}</p>
        <p class="">Latitude: {{ destination.latitude }}</p>
        <p class="">Longitude: {{ destination.longitude }}</p>
        <!-- Add weather data -->
        <p class="">Weather: {{ weather_data.weather.0.main }}</p>
        <p class="">Temperature: {{ weather_data.main.temp|floatformat:2 }}°C</p>
         <br>
        <!-- Add video YouTube -->
        {% if destination.youtube_url %}
        <div class="col-12">
            <div class="embed-responsive embed-responsive-16by9">
              {% if "youtu.be" in destination.youtube_url %}
                <iframe class="embed-responsive-item col-11" src="{{ destination.youtube_url|replace:'youtu.be,www.youtube.com/embed' }}" style="min-height:430px !important" allowfullscreen></iframe>
              {% elif "watch?v=" in destination.youtube_url %}
                <iframe class="embed-responsive-item col-11" src="{{ destination.youtube_url|replace:'watch?v=,embed/' }}"style="min-height:430px !important" allowfullscreen></iframe>
              {% else %}
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ destination.youtube_url }} col-11"style="min-height:430px !important" allowfullscreen></iframe>
              {% endif %}
            </div>
          </div>
          
    {% endif %}
        <br>
        <!-- Map Display -->
        <div class="destination-map" id="destination-map" style="width:800px; height:450px;"></div>
        <br><br>

        <!-- Add Facebook Share Button here -->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v8.0" nonce="kXj3s9Dk"></script>
<div class="fb-share-wrapper">
  <div class="fb-share-button custom-fb-share-button" data-href="https://yourwebsite.com/current-page-url" data-layout="button_count"></div>
</div>
        <br><br>

                <!-- Add the update and delete buttons here -->
                {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'update_destination' destination.id %}" class="btn btn-primary mb-5">Update</a>
                <a href="{% url 'delete_destination' destination.id %}" class="btn btn-danger mb-5">Delete</a>
                {% endif %}
        <br><br>

    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'add_review' destination.id %}">
        {% csrf_token %}
        <textarea class="input-review" name="review_text" placeholder="Write your review..."></textarea>
        <input class="submit-button" type="submit" value="Submit Review">
    </form>

    {% else %}
       <p>You must be logged in to post a review.</p>
    {% endif %}
    <br><br>

      <h2 class="reviews-title">User reviews</h2>
      <hr class="hr">
      <br>
      {% for review in reviews %}
      <div>
        <h6 class="user-reviews"><b>{{ review.user.username }}</b>:&nbsp; {{ review.review_text }}</h6>
        <p>{{ reviewdate_posted|date:"F j, Y, g:i a" }}</p>
       </div>
      {% endfor %}

    </div>
    <div class="col-sm-4">
        <div class="col-12"><h4 class="text-1">Related Sites</h4></div>
        <div class="col-12 ">
            {% for relat in relats %}
            <div class="col-12">
              <div class="card col-12 mb-2">
                <img src="/{{ relat.3 }}" class="card-img-top img-fluid" alt="{{ relat.1 }}">
                <div class="card-body">
                  <h5 class="card-title">{{ relat.1 }}</h5>
                  <p class="card-text">{{ relat.2 |truncatewords:21}}</p>
                  <a href="{% url 'destination_detail' relat.0 %}" class="btn-block col-12 btn btn-danger">Go</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
    </div>
</div>
<br><br>
{% endblock content %}

{% block extra_js %}
<script>
    var map = L.map('destination-map').setView([{{ destination.latitude }}, {{ destination.longitude }}], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([{{ destination.latitude }}, {{ destination.longitude }}]).addTo(map)
        .bindPopup('{{ destination.title }}').openPopup();
</script>
{% endblock extra_js %}

templates/email_notification.html
<h1>New Destination Created</h1>
<p>A new destination titled {{ destination.title }} has been created. Check it out!</p>
<img src="{{ destination.image.url }}" alt="{{ destination.title }}">
<p>{{ destination.description|truncatewords:50 }}...</p>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    
    body {
        background-image: url("{% static 'images/keraton kasepuhan.jpg' %}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-color: rgba(255,255,255,0.6);
        background-blend-mode: lighten;
    }
        #chat-button {
          position: fixed;
          bottom: 0;
          right: 0;
          height:70px;
          width: 100px;
          border-radius: 50px 50px 0 0; /* Membuat sudut melengkung pada bagian atas tombol */
        }
</style>

<div class="body-background my-auto d-flex align-items-center justify-content-center" style="height: 100vh;">
    <div class="overlay">
      <div class="form-container">
        <h1 class="form-title">Tell Us About Your Dream Vacation</h1>
        <div class="search-form">
          <form method="GET" action="{% url 'search' %}">
            <div class="row">
              <div class="col-5">
                <label for="category" class="form-label">Destinations</label>
                <select id="category" name="category" class="form-control">
                  <option value="">--- Select a category ---</option>
                  <option value="WR">Wisata Religi</option>
                  <option value="TW">Taman Wisata</option>
                  <option value="WA">Wisata Air</option>
                  <option value="WK">Wisata Kuliner</option>
                </select>
              </div>
              <div class="col-5">
                <label for="budget" class="form-label">Budget</label>
                <select id="budget" name="budget" class="form-control">
                  <option value="">--- Select a budget ---</option>
                  <option value="0-20000">0-20000</option>
                  <option value="20000-50000">20000-50000</option>
                  <option value="50000-100000">50000-100000</option>
                  <option value="100000-200000">100000-200000</option>
                </select>
              </div>
              <div class="col-2 d-flex align-items-end">
                <button type="submit" class="btn btn-dark search-button">Search</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  

<!-- Chat box -->
<div id="chatbox" style="display: none; position: fixed; bottom: 0; right: 0; width: 300px; height: 400px; background-color: white; border: 1px solid black; padding: 10px;">
    <div id="chat-header">
      <button id="minimize-button">Minimize</button>
      <button id="maximize-button">Maximize</button>
    </div>
    <div style="height: 80%; overflow-y: scroll;" id="chat-content">
    </div>
    <input id="chat-input" type="text" style="width: 100%; height: 10%;" placeholder="Type your message here">
  </div>

  <!-- Chat button -->
  <button id="chat-button"><b><ion-icon name="chatbubble-ellipses-outline"></ion-icon>&nbsp; Chat</b></button>


  <script>
    // Get the chatbox, chat content, chat input, chat button, and the minimize and maximize buttons
    var chatbox = document.getElementById("chatbox");
    var chatContent = document.getElementById("chat-content");
    var chatInput = document.getElementById("chat-input");
    var chatButton = document.getElementById("chat-button");
    var minimizeButton = document.getElementById("minimize-button");
    var maximizeButton = document.getElementById("maximize-button");

    // When the chat button is clicked, show the chatbox and hide the chat button
    chatButton.addEventListener("click", function() {
      chatbox.style.display = "block";
      chatButton.style.display = "none";
    });

    // When the minimize button is clicked, hide the chatbox and show the chat button
    minimizeButton.addEventListener("click", function() {
      chatbox.style.display = "none";
      chatButton.style.display = "block";
    });

    // When the maximize button is clicked, resize the chatbox to 25% of the screen
    maximizeButton.addEventListener("click", function() {
      chatbox.style.width = "25%";
      chatbox.style.height = "100%";
    });

    // When a message is typed and enter is pressed, add the message to the chat content
    chatInput.addEventListener("keydown", function(event) {
        if (event.key === "Enter") {
            var message = chatInput.value;
            chatContent.innerHTML += "<p><b>You:</b> " + message + "</p>";
            chatInput.value = "";

            // Send the message to the chatbot and get the response
            fetch('/chatbot_response/?message=' + message)
            .then(response => response.json())
            .then(data => {
                chatContent.innerHTML += "<p><b>Bot:</b> " + data.response + "</p>";
            });
        }
    });

  </script>

  {% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container mt-2">
    <div class="col-12 row">
        {% if destinations %}
            {% for destination in destinations %}
            <div class="col-4 mb-3">
                <div class="card ">
                    <div class="card-header bg-primary text-white">
                        <p class="text-center card-title">{{ destination.title }}</p>
                    </div>
                    <div class="card-body">
                        <img src="{{ destination.image.url }}" alt="{{ destination.title }}" style="width:100px; height:auto;" class="img-flex d-flex">
                        <p class="mt-1" >{{ destination.description|truncatewords:21 }}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'destination_detail' destination.id %}" class="btn col-12 btn-warning btn-block ">Continue</a>
                    </div>
                </div>
            </div>
            
            {% endfor %}
        {% else %}
            <h3>{{ message }}</h3>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/update_destination.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container mt-3 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <h2>Update Destination</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Update</button>
        <a href="{% url 'destination_detail' destination.id %}" class="btn btn-danger mt-3">Cancel</a>
    </form>
    {% endif %}
</div>

{% endblock content %}